# Generated by Django 3.1.7 on 2021-03-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0002_yazilarmodel_yorummodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EgitmenModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='egitmen_resimleri')),
                ('isim', models.CharField(max_length=50)),
                ('ünvan', models.CharField(max_length=60)),
                ('tanıma', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'Egitmen',
                'verbose_name_plural': 'Egitmenler',
                'db_table': 'Egitmen',
            },
        ),
    ]
