# Generated by Django 3.1.7 on 2021-03-31 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0004_auto_20210331_1815'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EgitmenTanıma',
        ),
    ]
