# Generated by Django 3.1.7 on 2021-03-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0005_delete_egitmentanıma'),
    ]

    operations = [
        migrations.CreateModel(
            name='KurslarGörüntüle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resim', models.ImageField(upload_to='kurs_resimleri')),
                ('baslik', models.CharField(max_length=50)),
                ('icerik', models.TextField(max_length=100)),
            ],
            options={
                'verbose_name': 'KursGörünlüte',
                'verbose_name_plural': 'KurslarGörüntüle',
                'db_table': 'KursGörüntüle',
            },
        ),
    ]
