# Generated by Django 3.1.7 on 2021-04-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0006_kurslargörüntüle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerslerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=20)),
                ('resim', models.ImageField(upload_to='ders_resimleri')),
                ('icerik', models.TextField(max_length=150)),
                ('ücret', models.CharField(max_length=20)),
                ('tür', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Dersler',
                'verbose_name_plural': 'Ders-Ekle',
                'db_table': 'DerslerTablo',
            },
        ),
        migrations.DeleteModel(
            name='KurslarGörüntüle',
        ),
    ]
