# Generated by Django 3.1.7 on 2021-04-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0011_derslermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DerslerModel',
        ),
    ]
